#ifndef OBJECT_LOADER_SHADER_LAYOUT_LOCATIONS_GLSL
#define OBJECT_LOADER_SHADER_LAYOUT_LOCATIONS_GLSL

#define UNIFORM_MATRICES_BINDING 0
#define VERTICES_LAYOUT_LOCATION 0
#define NORMALS_LAYOUT_LOCATION 1
#define TEX_COORDS_LAYOUT_LOCATION 2

#endif
